#!/usr/bin/env python

# Check if we're developing
try:
    import codega

except ImportError:
    import sys, os.path
    sys.path.append(os.path.dirname(__file__))

from codega.build import Builder
Builder.main()
