#!/usr/bin/env python

# Check if we're developing
try:
    import codega

except ImportError:
    import sys, os.path
    sys.path.append(os.path.dirname(__file__))

# MARK -- this comment is important, cgx pack will copy-paste the code below this
import sys
import codega.logger
from codega.commands import CommandMain

codega.logger.prepare()
rc = 0
if not CommandMain('cgx', helpstring = 'codega run-time script').run(sys.argv[1:]):
    rc = 1

exit(rc)
