#!/usr/bin/env bash

makedoc_typed()
{
  echo "creating $1 documentation (treeid $2)"
  epydoc --$1 --show-sourcecode -o "doc/$1" -n codega --graph all codega
}

makedoc()
{
  NAME="codega-$1-doc.tar.gz"

  makedoc_typed html $1
  tar czf $NAME doc
}

release()
{
  NAME="codega-$2.tar.gz"

  echo -n "git archive (treeid $1 archive $NAME) "
  git archive $1 | gzip > $NAME

  echo -n "self-contained (codega-$2) "
  ./cgx pack "codega-$2"

  makedoc $2
}

treeid=${1:-snapshot}
version=`cat VERSION`

if [ "$treeid" = "snapshot" ]
then
  snapshotid=`date +%Y%m%d.%H%M`
  tag="v$version-$snapshotid"

  echo -n "Creating snapshot $snapshotid... "
  release HEAD "$version-$snapshotid"
  echo "done"

  git tag -f $tag
else
  tag="v$version"

  echo -n "Creating release $snapshotid... "
  release ${treeid} ${version}
  echo "done"

  git tag -f ${tag}
fi
